### ISSUE TITLE
Ошибка генерации wordcloud

### ISSUE THREAD

**Issue by kvarts** [vlajnaya-mol/message-analyser#4]
Был запущен анализ переписки вк. Остальные опции не выбирал. Графики создавались пока не прервались на wordcloud.

Получил следующую ошибку:
```
2019-02-24 02:13:01,869 - barplot_words was created.

Task exception was never retrieved
future: <Task finished coro=<retrieve_and_analyse() done, defined at C:\Users\ivank\message-analyser\message_analyser\analyser.py:219> exception=ValueError('We need at least 1 word to plot a word cloud, got 0.',)>
Traceback (most recent call last):
  File "C:\Users\ivank\message-analyser\message_analyser\analyser.py", line 227, in retrieve_and_analyse
    await _analyse(msgs, your_name, target_name, words_file)
  File "C:\Users\ivank\message-analyser\message_analyser\analyser.py", line 203, in _analyse
    await _plot_all(msgs, your_name, target_name, results_directory, words_file)
  File "C:\Users\ivank\message-analyser\message_analyser\analyser.py", line 152, in _plot_all
    await _plot_words_distribution(filtered_msgs, your_name, target_name, results_directory, words)
  File "C:\Users\ivank\message-analyser\message_analyser\analyser.py", line 135, in _plot_words_distribution
    plt.wordcloud(msgs, words, results_directory)
  File "C:\Users\ivank\message-analyser\message_analyser\plotter.py", line 546, in wordcloud
    word_cloud.generate(all_words_string)
  File "C:\Users\ivank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wordcloud\wordcloud.py", line 605, in generate
    return self.generate_from_text(text)
  File "C:\Users\ivank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wordcloud\wordcloud.py", line 587, in generate_from_text
    self.generate_from_frequencies(words)
  File "C:\Users\ivank\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wordcloud\wordcloud.py", line 383, in generate_from_frequencies
    "got %d." % len(frequencies))
ValueError: We need at least 1 word to plot a word cloud, got 0.
```

**Comment by voloha-mil** [comment]
Сколько сообщений было извлечено с файла?

**Comment by voloha-mil** [comment]
И сколько слов в файле со словами?

**Comment by voloha-mil** [comment]
Пофиксил краш при отсутствии слов
